services:

  mail-dev:
    container_name: mail-dev-location
    image: maildev/maildev
    ports:
      - 1080-1080
      - 1025:1025

  redis:
    container_name: redis-car-joy
    image: redis:7-alpine
    ports:
      - 6379:6379

networks:
  pressing-net:
    driver: bridge
